@startuml 포트원 연동-결제

header Munute NextGen '24.12.30
footer 사운드플랫폼
title 포트원 연동-결제
autonumber

actor       회원
participant 결제창
boundary    포트원
participant 백엔드
boundary    포트원_웹훅

회원 -> 결제창: 결제 요청
activate 결제창
    결제창 -> 포트원: 결제 요청
    포트원 --> 결제창: 결제 결과
    결제창 -> 백엔드: 결제 결과 저장 요청
    activate 백엔드
        '백엔드 --> 포트원: 결제 결과 검증
        백엔드 --> 백엔드: 결제 결과 저장
        백엔드 --> 결제창: 결제 결과 저장 여부
    deactivate 백엔드
    결제창 -> 회원: 결제 완료 알림
deactivate 결제창

group 웹훅
    포트원_웹훅 --> 백엔드: 결제 결과 검증
    백엔드 --> 백엔드: 결제 결과 갱신
end

== 구독 연장 ==

group 주기적 자동 재결제
    백엔드 --> 포트원: 결제 요청
    포트원 --> 백엔드: 결제 결과
    백엔드 --> 백엔드: 결제 결과 저장

    group 웹훅
        포트원_웹훅 --> 백엔드: 결제 결과 검증
        백엔드 --> 백엔드: 결제 결과 갱신
    end
end
@enduml
