### 결제
POST https://checkout-service.prod.iamport.co/api/prepare/v2
accept: */*
accept-language: en-US,en;q=0.9
origin: http://localhost:8080
priority: u=1, i
referer: http://localhost:8080/
sec-ch-ua: "Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
Content-Type: application/json

{
  "data": {
    "storeId": "store-6575972a-e9b8-47aa-b1d5-a7b7c83a1a25",
    "_channelKey": "channel-key-5416059a-1aa8-4d17-a9ca-073808d2f6eb",
    "channelKey": "channel-key-056138e3-1a1e-40af-849d-e8316bca813a",
    "paymentId": "37e179958be6f600",
    "orderName": "김동석신발",
    "totalAmount": 1000,
    "currency": "USD",
    "payMethod": "CARD",
    "customData": {
      "item": "shoes"
    },
    "actionType": "REQUEST_PAY"
  },
  "sdkVersion": "1.28.13",
  "deviceInfo": {
    "platformType": "PLATFORM_TYPE_PC",
    "isIpad": false
  }
}

###

